import React from "react";
import {StyleSheet, View, Text, Image} from "react-native";

export default images ={
    "0_0": require("../assets/images/Cards/0_0.jpg"),
    "0_1": require("../assets/images/Cards/0_1.jpg"),
    "0_2": require("../assets/images/Cards/0_2.jpg"),
    "0_3": require("../assets/images/Cards/0_3.jpg"),
    "0_4": require("../assets/images/Cards/0_4.jpg"),
    "0_5": require("../assets/images/Cards/0_5.jpg"),
    "0_6": require("../assets/images/Cards/0_6.jpg"),
    "0_7": require("../assets/images/Cards/0_7.jpg"),
    "0_8": require("../assets/images/Cards/0_8.jpg"),
    "0_9": require("../assets/images/Cards/0_9.jpg"),
    "0_10": require("../assets/images/Cards/0_10.jpg"),
    "0_11": require("../assets/images/Cards/0_11.jpg"),
    "0_12": require("../assets/images/Cards/0_12.jpg"),
    "1_0": require("../assets/images/Cards/0_0.jpg"),
    "1_1": require("../assets/images/Cards/0_1.jpg"),
    "1_2": require("../assets/images/Cards/0_2.jpg"),
    "1_3": require("../assets/images/Cards/0_3.jpg"),
    "1_4": require("../assets/images/Cards/0_4.jpg"),
    "1_5": require("../assets/images/Cards/0_5.jpg"),
    "1_6": require("../assets/images/Cards/0_6.jpg"),
    "1_7": require("../assets/images/Cards/0_7.jpg"),
    "1_8": require("../assets/images/Cards/0_8.jpg"),
    "1_9": require("../assets/images/Cards/0_9.jpg"),
    "1_10": require("../assets/images/Cards/0_10.jpg"),
    "1_11": require("../assets/images/Cards/0_11.jpg"),
    "1_12": require("../assets/images/Cards/0_12.jpg"),
    "2_0": require("../assets/images/Cards/0_0.jpg"),
    "2_1": require("../assets/images/Cards/0_1.jpg"),
    "2_2": require("../assets/images/Cards/0_2.jpg"),
    "2_3": require("../assets/images/Cards/0_3.jpg"),
    "2_4": require("../assets/images/Cards/0_4.jpg"),
    "2_5": require("../assets/images/Cards/0_5.jpg"),
    "2_6": require("../assets/images/Cards/0_6.jpg"),
    "2_7": require("../assets/images/Cards/0_7.jpg"),
    "2_8": require("../assets/images/Cards/0_8.jpg"),
    "2_9": require("../assets/images/Cards/0_9.jpg"),
    "2_10": require("../assets/images/Cards/0_10.jpg"),
    "2_11": require("../assets/images/Cards/0_11.jpg"),
    "2_12": require("../assets/images/Cards/0_12.jpg"),
    "3_0": require("../assets/images/Cards/0_0.jpg"),
    "3_1": require("../assets/images/Cards/0_1.jpg"),
    "3_2": require("../assets/images/Cards/0_2.jpg"),
    "3_3": require("../assets/images/Cards/0_3.jpg"),
    "3_4": require("../assets/images/Cards/0_4.jpg"),
    "3_5": require("../ass3ets/images/Cards/0_5.jpg"),
    "3_6": require("../assets/images/Cards/0_6.jpg"),
    "3_7": require("../assets/images/Cards/0_7.jpg"),
    "3_8": require("../assets/images/Cards/0_8.jpg"),
    "3_9": require("../assets/images/Cards/0_9.jpg"),
    "3_10": require("../assets/images/Cards/0_10.jpg"),
    "3_11": require("../assets/images/Cards/0_11.jpg"),
    "3_12": require("../assets/images/Cards/0_12.jpg")
}